export const ADD_STUDENT='ADD_STUDENT';
export const DELETE_STUDENT='DELETE_STUDENT';
export const UPDATE_STUDENT='UPDATE_STUDENT';
export const ADD_TEACHER='ADD_TEACHER';
export const DELETE_TEACHER='DELETE_TEACHER';
export const UPDATE_TEACHER='UPDATE_TEACHER';
export const ADD_COURSE='ADD_COURSE';
export const DELETE_COURSE='DELETE_COURSE';
export const UPDATE_COURSE='UPDATE_COURSE';

export const TEACHER_ADD_ASSIGNMENT="TEACHER_ADD_ASSIGNMENT";
export const TEACHER_ADD_QUIZ="TEACHER_ADD_QUIZ";
export const TEACHER_ADD_MIDS="TEACHER_ADD_MIDS";
export const TEACHER_ADD_CLASSPARTICIPATION="TEACHER_ADD_CLASSPARTICIPATION";
export const TEACHER_ADD_FINALS="TEACHER_ADD_FINALS";
export const TEACHER_ADD_PROJECTPRESENTATION="TEACHER_ADD_PROJECTPRESENTATION";
export const TEACHER_ADD_PROJECTS="TEACHER_ADD_PROJECTS";

export const SET_STUDENT="SET_STUDENT";
export const SET_TEACHER="SET_TEACHER";
export const SET_COURSE="SET_COURSE";

export const DELETE_MARKS_TYPES="DELETE_MARKS_TYPES";
export const ADD_MARKS_TYPES="ADD_MARKS_TYPES";
export const SET_MARKS_TYPES="SET_MARKS_TYPES";

export const DELETE_SEMESTER="DELETE_SEMESTER";
export const ADD_SEMESTER="ADD_SEMESTER";
export const SET_SEMESTER="SET_SEMESTER";

export const DELETE_SECTION="DELETE_SECTION";
export const ADD_SECTION="ADD_SECTION";
export const SET_SECTION="SET_SECTION";

export const DELETE_STUDENT_SECTION="DELETE_STUDENT_SECTION";
export const ADD_STUDENT_SECTION="ADD_STUDENT_SECTION";
export const SET_STUDENT_SECTION="SET_STUDENT_SECTION";

export const DELETE_TEACHER_SECTION="DELETE_TEACHER_SECTION";
export const ADD_TEACHER_SECTION="ADD_TEACHER_SECTION";
export const SET_TEACHER_SECTION="SET_TEACHER_SECTION";

//STUDENTS INFORMATION 
export const GET_ANNOUNCEMENT="GET_ANNOUNCEMENT";
export const GET_COURSE_OULINE="GET_COURSE_OULINE";
export const GET_GRADE_BOOK="GET_GRADE_BOOK";

